CREATE TABLE IF NOT EXISTS {{ schema }}.listing_details (
    global_id TEXT,
    tiny_id TEXT,
    title TEXT,
    city TEXT,
    postcode TEXT,
    province TEXT,
    neighbourhood TEXT,
    municipality TEXT,
    price BIGINT,
    price_formatted TEXT,
    status TEXT,
    offering_type TEXT,
    object_type TEXT,
    house_type TEXT,
    construction_type TEXT,
    construction_year TEXT,
    energy_label TEXT,
    living_area INT,
    plot_area INT,
    bedrooms INT,
    rooms INT,
    description TEXT,
    publication_date TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    has_garden BOOLEAN,
    has_balcony BOOLEAN,
    has_solar_panels BOOLEAN,
    has_heat_pump BOOLEAN,
    has_roof_terrace BOOLEAN,
    is_energy_efficient BOOLEAN,
    is_monument BOOLEAN,
    url TEXT,
    photo_count INT,
    views INT,
    saves INT,
    raw_json JSONB,
    ingested_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (global_id, status)
);
