create table if not exists {{ schema }}.listing_details (
    global_id text,
    tiny_id text,
    title text,
    city text,
    postcode text,
    province text,
    neighbourhood text,
    municipality text,
    price bigint,
    price_formatted text,
    status text,
    offering_type text,
    object_type text,
    house_type text,
    construction_type text,
    construction_year text,
    energy_label text,
    living_area int,
    plot_area int,
    bedrooms int,
    rooms int,
    description text,
    publication_date text,
    latitude double precision,
    longitude double precision,
    has_garden boolean,
    has_balcony boolean,
    has_solar_panels boolean,
    has_heat_pump boolean,
    has_roof_terrace boolean,
    is_energy_efficient boolean,
    is_monument boolean,
    url text,
    photo_count int,
    views int,
    saves int,
    raw_json jsonb,
    ingested_at timestamptz default now(),
    last_fetched_at timestamptz default now(),
    is_stale boolean default false,
    unique (global_id, status)
);
