insert into {{ schema }}.listing_details (
    global_id, tiny_id, title, city, postcode, province,
    neighbourhood, municipality, price, price_formatted,
    status, offering_type, object_type, house_type,
    construction_type, construction_year, energy_label,
    living_area, plot_area, bedrooms, rooms, description,
    publication_date, latitude, longitude,
    has_garden, has_balcony, has_solar_panels, has_heat_pump,
    has_roof_terrace, is_energy_efficient, is_monument,
    url, photo_count, views, saves, raw_json
)
values (
    :global_id, :tiny_id, :title, :city, :postcode, :province,
    :neighbourhood, :municipality, :price, :price_formatted,
    :status, :offering_type, :object_type, :house_type,
    :construction_type, :construction_year, :energy_label,
    :living_area, :plot_area, :bedrooms, :rooms, :description,
    :publication_date, :latitude, :longitude,
    :has_garden, :has_balcony, :has_solar_panels, :has_heat_pump,
    :has_roof_terrace, :is_energy_efficient, :is_monument,
    :url, :photo_count, :views, :saves, :raw_json
)
on conflict (global_id, status) do update set
    tiny_id = excluded.tiny_id,
    title = excluded.title,
    city = excluded.city,
    postcode = excluded.postcode,
    province = excluded.province,
    neighbourhood = excluded.neighbourhood,
    municipality = excluded.municipality,
    price = excluded.price,
    price_formatted = excluded.price_formatted,
    offering_type = excluded.offering_type,
    object_type = excluded.object_type,
    house_type = excluded.house_type,
    construction_type = excluded.construction_type,
    construction_year = excluded.construction_year,
    energy_label = excluded.energy_label,
    living_area = excluded.living_area,
    plot_area = excluded.plot_area,
    bedrooms = excluded.bedrooms,
    rooms = excluded.rooms,
    description = excluded.description,
    publication_date = excluded.publication_date,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    has_garden = excluded.has_garden,
    has_balcony = excluded.has_balcony,
    has_solar_panels = excluded.has_solar_panels,
    has_heat_pump = excluded.has_heat_pump,
    has_roof_terrace = excluded.has_roof_terrace,
    is_energy_efficient = excluded.is_energy_efficient,
    is_monument = excluded.is_monument,
    url = excluded.url,
    photo_count = excluded.photo_count,
    views = excluded.views,
    saves = excluded.saves,
    raw_json = excluded.raw_json,
    ingested_at = now(),
    last_fetched_at = now(),
    is_stale = false
